[pytest]
python_files = *_test.py test_*.py
python_classes = Test*
python_functions = test_*
markers =
    courses: Маркировка для проверки курсов
    regression: Макрировка для регрессивных тестов
    authorization: Маркировка для тестов на авторизацию
    registration: Маркировка для тестов на регистрацию
    dashboard: Маркировка для тестов, связанных с рабочей панелью.